/* Minimal grammatical facts from the user-supplied document; no source sentences. */
(function (global) {
  "use strict";
  const data = {
  "source_file": "ML_meankieli_perfect_imperfect_sentences.docx",
  "source_sha256": "03b293161bdba68cf160f4cd630c741d35dcd372e8561e2b6c966ee2b8e5e525",
  "source_note": "The document states that its sentences were composed. Direct forms are document examples, not independent corpus attestation or analyzer validation.",
  "rows": [
    {"id":"T2.R1","table":2,"row":1,"source_lemma":"antaa","lemma":"antaa","kind":"participle","slot":"sg","surface":"antanu","disposition":"direct"},
    {"id":"T2.R2","table":2,"row":2,"source_lemma":"alkaa","lemma":"alkaa","kind":"participle","slot":"sg","surface":"alkanu","disposition":"direct"},
    {"id":"T2.R3","table":2,"row":3,"source_lemma":"käsittää","lemma":"käsittää","kind":"participle","slot":"sg","surface":"käsittäny","disposition":"direct"},
    {"id":"T2.R4","table":2,"row":4,"source_lemma":"ymmärtää","lemma":"ymmärtää","kind":"participle","slot":"sg","surface":"ymmärtäny","disposition":"direct"},
    {"id":"T2.R5","table":2,"row":5,"source_lemma":"unheuttaa","lemma":"unheuttaa","kind":"participle","slot":"sg","surface":"unhouttanu","disposition":"direct"},
    {"id":"T2.R6","table":2,"row":6,"source_lemma":"herättää","lemma":"herättää","kind":"participle","slot":"sg","surface":"herättäny","disposition":"direct"},
    {"id":"T2.R7","table":2,"row":7,"source_lemma":"ostaa","lemma":"ostaa","kind":"participle","slot":"pl","surface":"ostanheet","disposition":"direct"},
    {"id":"T2.R8","table":2,"row":8,"source_lemma":"kirjottaa","lemma":"kirjottaa","kind":"participle","slot":"sg","surface":"kirjottanu","disposition":"direct"},
    {"id":"T2.R9","table":2,"row":9,"source_lemma":"rakastaa","lemma":"rakastaa","kind":"participle","slot":"sg","surface":"rakastanu","disposition":"direct"},
    {"id":"T2.R10","table":2,"row":10,"source_lemma":"auttaa","lemma":"auttaa","kind":"participle","slot":"sg","surface":"auttanu","disposition":"direct"},
    {"id":"T5.R1","table":5,"row":1,"source_lemma":"antaa","lemma":"antaa","kind":"past","slot":"se/hään","surface":"anto","disposition":"direct"},
    {"id":"T5.R2","table":5,"row":2,"source_lemma":"alkaa","lemma":"alkaa","kind":"past","slot":"se/hään","surface":"alko","disposition":"direct"},
    {"id":"T5.R3","table":5,"row":3,"source_lemma":"käsittää","lemma":"käsittää","kind":"past","slot":"mie","surface":"käsitin","disposition":"direct"},
    {"id":"T5.R4","table":5,"row":4,"source_lemma":"ymmärtää","lemma":"ymmärtää","kind":"past","slot":"se/hään","surface":"ymmärsi","disposition":"direct"},
    {"id":"T5.R5","table":5,"row":5,"source_lemma":"unheuttaa","lemma":"unheuttaa","kind":"past","slot":"se/hään","surface":"unhoutti","disposition":"direct"},
    {"id":"T5.R6","table":5,"row":6,"source_lemma":"herättää","lemma":"herättää","kind":"past","slot":"se/hään","surface":"herätti","disposition":"direct"},
    {"id":"T5.R7","table":5,"row":7,"source_lemma":"ostaa","lemma":"ostaa","kind":"past","slot":"se/hään","surface":"osti","disposition":"direct"},
    {"id":"T5.R8","table":5,"row":8,"source_lemma":"kirjottaa","lemma":"kirjottaa","kind":"past","slot":"se/hään","surface":"kirjotti","disposition":"direct"},
    {"id":"T5.R9","table":5,"row":9,"source_lemma":"rakastaa","lemma":"rakastaa","kind":"past","slot":"se/hään","surface":"rakasti","disposition":"direct"},
    {"id":"T5.R10","table":5,"row":10,"source_lemma":"auttaa","lemma":"auttaa","kind":"past","slot":"met","surface":"autoima","disposition":"direct"},
    {"id":"T9.R1","table":9,"row":1,"source_lemma":"huomata","lemma":"huomata","kind":"participle","slot":"sg","surface":"huomanu","disposition":"direct"},
    {"id":"T9.R2","table":9,"row":2,"source_lemma":"hypätä","lemma":"hypätä","kind":"participle","slot":"sg","surface":"hypänny","disposition":"direct"},
    {"id":"T9.R3","table":9,"row":3,"source_lemma":"tarjota","lemma":"tarjota","kind":"participle","slot":"sg","surface":"tarjonnu","disposition":"direct"},
    {"id":"T9.R4","table":9,"row":4,"source_lemma":"haluta","lemma":"haluta","kind":"participle","slot":"sg","surface":"halunnu","disposition":"direct"},
    {"id":"T9.R5","table":9,"row":5,"source_lemma":"pölätä","lemma":"pölätä","kind":"participle","slot":"sg","surface":"pölänny","disposition":"direct"},
    {"id":"T9.R6","table":9,"row":6,"source_lemma":"hakata","lemma":"hakata","kind":"participle","slot":"sg","surface":"hakannu","disposition":"direct"},
    {"id":"T9.R7","table":9,"row":7,"source_lemma":"maata","lemma":"maata","kind":"participle","slot":"sg","surface":"maanu","disposition":"direct"},
    {"id":"T9.R8","table":9,"row":8,"source_lemma":"kaota","lemma":"kaota","kind":"participle","slot":"sg","surface":"kaonu","disposition":"direct"},
    {"id":"T12.R1","table":12,"row":1,"source_lemma":"havata","lemma":"havata","kind":"past","slot":"se/hään","surface":"havati","disposition":"direct"},
    {"id":"T12.R2","table":12,"row":2,"source_lemma":"hypätä","lemma":"hypätä","kind":"past","slot":"se/hään","surface":"hyppäsi","disposition":"direct"},
    {"id":"T12.R3","table":12,"row":3,"source_lemma":"tarjota","lemma":"tarjota","kind":"past","slot":"se/hään","surface":"tarjosi","disposition":"direct"},
    {"id":"T12.R4","table":12,"row":4,"source_lemma":"haluta","lemma":"haluta","kind":"past","slot":"se/hään","surface":"halusi","disposition":"direct"},
    {"id":"T12.R5","table":12,"row":5,"source_lemma":"pölätä","lemma":"pölätä","kind":"past","slot":"se/hään","surface":"pölkäsi","disposition":"direct"},
    {"id":"T12.R6","table":12,"row":6,"source_lemma":"määrätä","lemma":"määrätä","kind":"past","slot":"se/hään","surface":"määräsi","disposition":"direct"},
    {"id":"T12.R7","table":12,"row":7,"source_lemma":"arvata","lemma":"arvata","kind":"past","slot":"mie","surface":"arvasin","disposition":"direct"},
    {"id":"T12.R8","table":12,"row":8,"source_lemma":"hakata","lemma":"hakata","kind":"past","slot":"se/hään","surface":"hakkasi","disposition":"direct"},
    {"id":"T12.R9","table":12,"row":9,"source_lemma":"maata","lemma":"maata","kind":"past","slot":"se/hään","surface":"makasi","disposition":"direct"},
    {"id":"T12.R10","table":12,"row":10,"source_lemma":"kaota","lemma":"kaota","kind":"past","slot":"se/hään","surface":"katosi","disposition":"direct"},
    {"id":"T16.R1","table":16,"row":1,"source_lemma":"saa’a","lemma":"saa’a","kind":"participle","slot":"sg","surface":"saanu","disposition":"direct"},
    {"id":"T16.R2","table":16,"row":2,"source_lemma":"myyä","lemma":"myyä","kind":"participle","slot":"sg","surface":"myyny","disposition":"direct"},
    {"id":"T16.R3","table":16,"row":3,"source_lemma":"jua","lemma":"jua","kind":"participle","slot":"sg","surface":"juonu","disposition":"direct"},
    {"id":"T16.R4","table":16,"row":4,"source_lemma":"tehjä","lemma":"tehä","kind":"participle","slot":"sg","surface":"tehny","disposition":"visible-variant"},
    {"id":"T16.R5","table":16,"row":5,"source_lemma":"nähjä","lemma":"nähä","kind":"participle","slot":"sg","surface":"nähny","disposition":"visible-variant"},
    {"id":"T16.R6","table":16,"row":6,"source_lemma":"syä","lemma":"syä","kind":"participle","slot":"sg","surface":"syöny","disposition":"direct"},
    {"id":"T16.R7","table":16,"row":7,"source_lemma":"lyä","lemma":"lyä","kind":"participle","slot":"sg","surface":"lyöny","disposition":"direct"},
    {"id":"T16.R8","table":16,"row":8,"source_lemma":"käyä","lemma":"käyä","kind":"participle","slot":"sg","surface":"käyny","disposition":"direct"},
    {"id":"T16.R9","table":16,"row":9,"source_lemma":"jää’ä","lemma":"jää’ä","kind":"participle","slot":"sg","surface":"jääny","disposition":"direct"},
    {"id":"T19.R1","table":19,"row":1,"source_lemma":"saa’a","lemma":"saa’a","kind":"past","slot":"se/hään","surface":"sai","disposition":"direct"},
    {"id":"T19.R2","table":19,"row":2,"source_lemma":"myyä","lemma":"myyä","kind":"past","slot":"net/het","surface":"myit","disposition":"direct"},
    {"id":"T19.R3","table":19,"row":3,"source_lemma":"jua","lemma":"jua","kind":"past","slot":"se/hään","surface":"joi","disposition":"direct"},
    {"id":"T19.R4","table":19,"row":4,"source_lemma":"voia","lemma":"voia","kind":"past","slot":"se/hään","surface":"saatto","disposition":"lexical-substitution"},
    {"id":"T19.R5","table":19,"row":5,"source_lemma":"tehjä","lemma":"tehä","kind":"past","slot":"mie","surface":"tehin","disposition":"visible-variant"},
    {"id":"T19.R6","table":19,"row":6,"source_lemma":"nähjä","lemma":"nähä","kind":"past","slot":"met","surface":"näimä","disposition":"visible-variant"},
    {"id":"T19.R7","table":19,"row":7,"source_lemma":"syä","lemma":"syä","kind":"past","slot":"net/het","surface":"söit","disposition":"direct"},
    {"id":"T19.R8","table":19,"row":8,"source_lemma":"lyä","lemma":"lyä","kind":"past","slot":"se/hään","surface":"löi","disposition":"direct"},
    {"id":"T19.R9","table":19,"row":9,"source_lemma":"käyä","lemma":"käyä","kind":"past","slot":"mie","surface":"kävin","disposition":"direct"},
    {"id":"T19.R10","table":19,"row":10,"source_lemma":"jää’ä","lemma":"jää’ä","kind":"past","slot":"met","surface":"jäimä","disposition":"direct"},
    {"id":"T23.R1","table":23,"row":1,"source_lemma":"nousta","lemma":"nousta","kind":"participle","slot":"sg","surface":"noussu","disposition":"direct"},
    {"id":"T23.R2","table":23,"row":2,"source_lemma":"pestä","lemma":"pestä","kind":"participle","slot":"sg","surface":"pessy","disposition":"direct"},
    {"id":"T23.R3","table":23,"row":3,"source_lemma":"laukkoa","lemma":"laukkoa","kind":"participle","slot":"sg","surface":"laukkonu","disposition":"direct"},
    {"id":"T23.R4","table":23,"row":4,"source_lemma":"päästä","lemma":"päästä","kind":"participle","slot":"pl","surface":"päässeet","disposition":"direct"},
    {"id":"T23.R5","table":23,"row":5,"source_lemma":"purra","lemma":"purra","kind":"participle","slot":"sg","surface":"purru","disposition":"direct"},
    {"id":"T23.R6","table":23,"row":6,"source_lemma":"murehtia","lemma":"murehtia","kind":"participle","slot":"sg","surface":"murehtinu","disposition":"direct"},
    {"id":"T23.R7","table":23,"row":7,"source_lemma":"kusta","lemma":"kusta","kind":"participle","slot":"sg","surface":"kussu","disposition":"direct"},
    {"id":"T23.R8","table":23,"row":8,"source_lemma":"nousta ylös","lemma":"nousta","kind":"participle","slot":"sg","surface":"noussu","disposition":"direct"},
    {"id":"T23.R9","table":23,"row":9,"source_lemma":"päästä irti","lemma":"päästä","kind":"participle","slot":"sg","surface":"päässy","disposition":"direct"},
    {"id":"T23.R10","table":23,"row":10,"source_lemma":"laukoa pois","lemma":"laukoa","kind":"participle","slot":"sg","surface":"laukonu","disposition":"direct"},
    {"id":"T25.R1","table":25,"row":1,"source_lemma":"nousta","lemma":"nousta","kind":"past","slot":"se/hään","surface":"nousi","disposition":"direct"},
    {"id":"T25.R2","table":25,"row":2,"source_lemma":"pestä","lemma":"pestä","kind":"past","slot":"se/hään","surface":"pesi","disposition":"direct"},
    {"id":"T25.R3","table":25,"row":3,"source_lemma":"juoksea","lemma":"juoksea","kind":"past","slot":"se/hään","surface":"juoksi/laukko","disposition":"ambiguous-lemma"},
    {"id":"T25.R4","table":25,"row":4,"source_lemma":"päästä","lemma":"päästä","kind":"past","slot":"se/hään","surface":"pääsi","disposition":"direct"},
    {"id":"T25.R5","table":25,"row":5,"source_lemma":"purra","lemma":"purra","kind":"past","slot":"se/hään","surface":"puri","disposition":"direct"},
    {"id":"T25.R6","table":25,"row":6,"source_lemma":"surra","lemma":"surra","kind":"past","slot":"se/hään","surface":"murehti","disposition":"lexical-substitution"},
    {"id":"T25.R7","table":25,"row":7,"source_lemma":"kusta","lemma":"kusta","kind":"past","slot":"se/hään","surface":"kusi","disposition":"direct"},
    {"id":"T25.R8","table":25,"row":8,"source_lemma":"nousta ylös","lemma":"nousta","kind":"past","slot":"se/hään","surface":"nousi","disposition":"direct"},
    {"id":"T25.R9","table":25,"row":9,"source_lemma":"päästä irti","lemma":"päästä","kind":"past","slot":"se/hään","surface":"pääsi","disposition":"direct"},
    {"id":"T25.R10","table":25,"row":10,"source_lemma":"juoksea pois","lemma":"juoksea","kind":"past","slot":"se/hään","surface":"juoksi/laukko","disposition":"ambiguous-lemma"},
    {"id":"T28.R1","table":28,"row":1,"source_lemma":"tulla","lemma":"tulla","kind":"participle","slot":"sg","surface":"tullu","disposition":"direct"},
    {"id":"T28.R2","table":28,"row":2,"source_lemma":"mennä","lemma":"mennä","kind":"participle","slot":"sg","surface":"menny","disposition":"direct"},
    {"id":"T28.R3","table":28,"row":3,"source_lemma":"aatela","lemma":"aatela","kind":"participle","slot":"sg","surface":"hunderanu","disposition":"lexical-substitution"},
    {"id":"T28.R4","table":28,"row":4,"source_lemma":"olla","lemma":"olla","kind":"participle","slot":"sg","surface":"ollu","disposition":"direct"},
    {"id":"T28.R5","table":28,"row":5,"source_lemma":"kuolla","lemma":"kuolla","kind":"participle","slot":"sg","surface":"kuollu","disposition":"direct"},
    {"id":"T28.R6","table":28,"row":6,"source_lemma":"panna","lemma":"panna","kind":"participle","slot":"sg","surface":"pannu","disposition":"direct"},
    {"id":"T28.R7","table":28,"row":7,"source_lemma":"purra","lemma":"purra","kind":"participle","slot":"sg","surface":"purru","disposition":"direct"},
    {"id":"T28.R8","table":28,"row":8,"source_lemma":"surra","lemma":"surra","kind":"participle","slot":"sg","surface":"murehtinu","disposition":"lexical-substitution"},
    {"id":"T28.R9","table":28,"row":9,"source_lemma":"ajatella","lemma":"ajatella","kind":"participle","slot":"sg","surface":"ajatellu","disposition":"direct"},
    {"id":"T28.R10","table":28,"row":10,"source_lemma":"kuunnella","lemma":"kuunnella","kind":"participle","slot":"sg","surface":"kuunnellu","disposition":"direct"},
    {"id":"T31.R1","table":31,"row":1,"source_lemma":"tulla","lemma":"tulla","kind":"past","slot":"se/hään","surface":"tuli","disposition":"direct"},
    {"id":"T31.R2","table":31,"row":2,"source_lemma":"mennä","lemma":"mennä","kind":"past","slot":"mie","surface":"menin","disposition":"direct"},
    {"id":"T31.R3","table":31,"row":3,"source_lemma":"aatela","lemma":"aatela","kind":"past","slot":"se/hään","surface":"aatteli","disposition":"direct"},
    {"id":"T31.R4","table":31,"row":4,"source_lemma":"olla","lemma":"olla","kind":"past","slot":"se/hään","surface":"oli","disposition":"direct"},
    {"id":"T31.R5","table":31,"row":5,"source_lemma":"kuolla","lemma":"kuolla","kind":"past","slot":"se/hään","surface":"kuoli","disposition":"direct"},
    {"id":"T31.R6","table":31,"row":6,"source_lemma":"panna","lemma":"panna","kind":"past","slot":"mie","surface":"panin","disposition":"direct"},
    {"id":"T31.R7","table":31,"row":7,"source_lemma":"purra","lemma":"purra","kind":"past","slot":"se/hään","surface":"puri","disposition":"direct"},
    {"id":"T31.R8","table":31,"row":8,"source_lemma":"surra","lemma":"surra","kind":"past","slot":"se/hään","surface":"murehti","disposition":"lexical-substitution"},
    {"id":"T31.R9","table":31,"row":9,"source_lemma":"muistaa","lemma":"muistaa","kind":"past","slot":"mie","surface":"muistin","disposition":"direct"},
    {"id":"T31.R10","table":31,"row":10,"source_lemma":"kuunnella","lemma":"kuunnella","kind":"past","slot":"met","surface":"kuntelima","disposition":"direct"},
    {"id":"T36.R1","table":36,"row":1,"source_lemma":"tarvita / tarttea","lemma":"tarttea","kind":"participle","slot":"sg","surface":"tarttenu","disposition":"variant-specific"},
    {"id":"T36.R2","table":36,"row":2,"source_lemma":"häiritä","lemma":"häiritä","kind":"participle","slot":"sg","surface":"häirinny","disposition":"direct"},
    {"id":"T36.R3","table":36,"row":3,"source_lemma":"valita","lemma":"valita","kind":"participle","slot":"sg","surface":"valinnu","disposition":"direct"},
    {"id":"T36.R4","table":36,"row":4,"source_lemma":"selitää","lemma":"selitää","kind":"participle","slot":"sg","surface":"selitäny","disposition":"direct"},
    {"id":"T36.R5","table":36,"row":5,"source_lemma":"tulkita","lemma":"tulkita","kind":"participle","slot":"sg","surface":"tulkinnu","disposition":"direct"},
    {"id":"T36.R6","table":36,"row":6,"source_lemma":"tuomita","lemma":"tuomita","kind":"participle","slot":"passive","surface":"tuomittu","disposition":"direct"},
    {"id":"T36.R7","table":36,"row":7,"source_lemma":"hoitaa","lemma":"hoitaa","kind":"participle","slot":"sg","surface":"hoitanu","disposition":"direct"},
    {"id":"T39.R1","table":39,"row":1,"source_lemma":"tarvita / tarttea","lemma":"tarttea","kind":"past","slot":"mie","surface":"tarttin","disposition":"variant-specific"},
    {"id":"T39.R2","table":39,"row":2,"source_lemma":"häiritä","lemma":"häiritä","kind":"past","slot":"se/hään","surface":"häiritti","disposition":"direct"},
    {"id":"T39.R3","table":39,"row":3,"source_lemma":"valita","lemma":"valita","kind":"past","slot":"se/hään","surface":"valiti","disposition":"direct"},
    {"id":"T39.R4","table":39,"row":4,"source_lemma":"tulkita","lemma":"tulkita","kind":"past","slot":"mie","surface":"tulkittin","disposition":"direct"},
    {"id":"T39.R5","table":39,"row":5,"source_lemma":"tuomita","lemma":"tuomita","kind":"past","slot":"net/het","surface":"tuomit","disposition":"direct"},
    {"id":"T39.R6","table":39,"row":6,"source_lemma":"hoitaa","lemma":"hoitaa","kind":"past","slot":"se/hään","surface":"hoiti","disposition":"direct"},
    {"id":"T44.R1","table":44,"row":1,"source_lemma":"vanheta","lemma":"vanheta","kind":"participle","slot":"sg","surface":"vanhaintunu","disposition":"direct"},
    {"id":"T44.R2","table":44,"row":2,"source_lemma":"lämmittä","lemma":"lämmittä","kind":"participle","slot":"sg","surface":"lämpiny","disposition":"ambiguous-lemma"},
    {"id":"T44.R3","table":44,"row":3,"source_lemma":"kylmetä","lemma":"kylmetä","kind":"participle","slot":"sg","surface":"kylmeny","disposition":"direct"},
    {"id":"T44.R4","table":44,"row":4,"source_lemma":"nuoreta","lemma":"nuoreta","kind":"participle","slot":"sg","surface":"nuorentunu","disposition":"unresolved-stem"},
    {"id":"T44.R5","table":44,"row":5,"source_lemma":"lyhetä","lemma":"lyhetä","kind":"participle","slot":"pl","surface":"lyhehneet","disposition":"direct"},
    {"id":"T44.R6","table":44,"row":6,"source_lemma":"vaaleta","lemma":"vaaleta","kind":"participle","slot":"sg","surface":"vaalenu","disposition":"direct"},
    {"id":"T44.R7","table":44,"row":7,"source_lemma":"tummeta","lemma":"tummeta","kind":"participle","slot":"sg","surface":"tummistunu","disposition":"unresolved-stem"},
    {"id":"T44.R8","table":44,"row":8,"source_lemma":"heiketä","lemma":"heiketä","kind":"participle","slot":"sg","surface":"heikonu","disposition":"direct"},
    {"id":"T44.R9","table":44,"row":9,"source_lemma":"laiheta","lemma":"laiheta","kind":"participle","slot":"sg","surface":"laihtunu","disposition":"unresolved-stem"},
    {"id":"T47.R1","table":47,"row":1,"source_lemma":"vanheta","lemma":"vanheta","kind":"past","slot":"se/hään","surface":"vanhentu","disposition":"direct"},
    {"id":"T47.R2","table":47,"row":2,"source_lemma":"lämmetä","lemma":"lämmetä","kind":"past","slot":"se/hään","surface":"lämpeni","disposition":"direct"},
    {"id":"T47.R3","table":47,"row":3,"source_lemma":"kylmetä","lemma":"kylmetä","kind":"past","slot":"se/hään","surface":"kylmisty","disposition":"direct"},
    {"id":"T47.R4","table":47,"row":4,"source_lemma":"nuoreta","lemma":"nuoreta","kind":"past","slot":"se/hään","surface":"näytti","disposition":"lexical-substitution"},
    {"id":"T47.R5","table":47,"row":5,"source_lemma":"lyhetä","lemma":"lyhetä","kind":"past","slot":"se/hään","surface":"lyhenty","disposition":"direct"},
    {"id":"T47.R6","table":47,"row":6,"source_lemma":"vaaleta","lemma":"vaaleta","kind":"past","slot":"se/hään","surface":"vaalentu","disposition":"direct"},
    {"id":"T47.R7","table":47,"row":7,"source_lemma":"heiketä","lemma":"heiketä","kind":"past","slot":"se/hään","surface":"heikosi","disposition":"direct"},
    {"id":"T47.R8","table":47,"row":8,"source_lemma":"laihtua","lemma":"laihtua","kind":"past","slot":"se/hään","surface":"laihtu","disposition":"direct"},
    {"id":"P33","paragraph":33,"source_lemma":"aatela","lemma":"aatela","kind":"past","slot":"mie","surface":"aatelin","disposition":"direct"}
  ],
  "stems": {"rakastaa": ["rakasti", "T5.R9", "all"], "auttaa": ["autoi", "T5.R10", "weak"], "pölätä": ["pölkäsi", "T12.R5", "all"], "määrätä": ["määräsi", "T12.R6", "all"], "arvata": ["arvasi", "T12.R7", "all"], "kaota": ["katosi", "T12.R10", "all"], "lyä": ["löi", "T19.R8", "all"], "jää’ä": ["jäi", "T19.R10", "all"], "kusta": ["kusi", "T25.R7", "all"], "kuolla": ["kuoli", "T31.R5", "all"], "panna": ["pani", "T31.R6", "all"], "purra": ["puri", "T31.R7", "all"], "muistaa": ["muisti", "T31.R9", "all"], "kuunnella": ["kunteli", "T31.R10", "all"], "tulkita": ["tulkitti", "T39.R4", "weak"]},
  "aliases": {"tehjä": "tehä", "nähjä": "nähä"},
  "blocked_rule_lemmas": ["surra"]
};
  function freeze(value) { if (value && typeof value === "object") { Object.values(value).forEach(freeze); Object.freeze(value); } return value; }
  global.MeanKieliPastExampleData = freeze(data);
})(window);
